spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.com.hireready=INFO

jwt.secret=${JWT_SECRET}

app.frontend.url=${FRONTEND_URL}