spring.datasource.url=jdbc:postgresql://localhost:5432/db_HireReady
spring.datasource.username=postgres
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=SElSRV9SRUFEWV9BUlFVSV9XRUJfVVBDX0lOR0VOSUVSSUFfU0lTVEVNQVNfREVfSU5GT1JNQUNJT04K

app.frontend.url=*